### ISSUE TITLE
Request work

### ISSUE THREAD

**Issue by samthegitguy** [samthegitguy/password-manager-one#5]
**Is your feature request related to a problem? Please describe.**
It is hard to merge master into working every time you find the commit works

**Describe the solution you'd like**
Using github actions to automagically merge from master to working

**Describe alternatives you've considered**
Manual merging

**Additional context**
None
@tjsfdc

**Comment by tjsfdc** [comment]
lets just work in master

**Comment by samthegitguy** [comment]
Might be ok for you but semantics is a top importance for me, the same reason i asked you not to move manifest into src on commit 227f112 . It comes back to bite you later.
227f112d83c26923477986e92def43168b1c4e00 
> Manifest should be in root. Manifest only has to do with the jar file, it will not help with actions.
> If you wish to compress to jar please read CONTRIUBTING.md for information on how to use it in the root. Replace the command in the yml file with the one i have suggested. i have reverted your commit.

**Comment by samthegitguy** [comment]
I have tested on local windows machine and it all seems to work.
Try using these commands: you can simply copy paste them if you can't open contributing.md
```
javac src/*.java -d bin
javadoc *.java -d docs
jar cmf manifest.txt program.jar bin/*.class docs assets
# Move jar (command varies by system)
git add * && git commit -m 'Update bin and docs files for release'
# Create release on github or use git tag. Attach jar and classes.
```
```

**Comment by samthegitguy** [comment]
@tjsfdc

**Comment by tjsfdc** [comment]
build and deploy pipeline fixed.

**Comment by samthegitguy** [comment]
Thank you!
